version: "3.1"
services:
  database:
    image: mariadb:10.5
    ports:
      - "3310:3306"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_USER=root"
      - "MYSQL_ROOT_PASSWORD=123456789"
      - "MYSQL_DATABASE=db"